apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pushgateway-perf-monitoring
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-sira-tenant/perf-monitoring/pushgateway-perf-monitoring@sha256:d99894907ffdce343965c4f2d95bb2dad4bf2d732c15940ca682600ebc501b0e
        name: perf-pushgateway
        resources: {}
status: {}
